### ISSUE TITLE
"You already voted on this request." message on posts never voted on before

### ISSUE THREAD

**Issue by hotpotcoldspag** [OpenYiff/Kemono2#104]
Even choosing a random post deep in the list, when attempting to vote (pressing the blue `+` button), [this](https://github.com/OpenYiff/Kemono2/blob/5deb7b6b1a3915abf2f301c42cd36ca593679da2/src/pages/legacy.py#L321) error appears.

**Comment by Thotfodder** [comment]
I think everybody has been experiencing that problem too.

**Comment by BassOfBass** [comment]
The request page got nuked, so suffice to say the issue is "solved".
