### ISSUE TITLE
/app/development/assets does not get automatically created/filled when starting the dev docker setup

### ISSUE THREAD

**Issue by C0rn3j** [OpenYiff/Kemono2#166]
![image](https://user-images.githubusercontent.com/1641362/159059423-80cb008e-c327-4e7c-8f94-36c7bb239edc.png)

```
https://t.me/kemonoparty/259830
Ace of Nine, [17/03/2022 23:50]
you have to create a /archiver/development/assets folder and put an image file there
that is an oversight of test importer
```
It looks like putting an image file is not necessary, but the folder does need to be created.

**Comment by BassOfBass** [comment]
Fixed in https://github.com/OpenYiff/Kemono2/commit/8ba6f2edea43cd00cc5ee6c6fdd3344cceac7f3c
