### ISSUE TITLE
Your App Steals from Content Creators

### ISSUE THREAD

**Issue by EricGallagher** [OpenYiff/Kemono2#197]
Sad that you use your coding abilities to do something low like this. Your site has been reported to your host. If taken down, I will continue to report your site to any company that you try to host your site under in the future.

**Comment by jojo935** [comment]
Good job the host we use is in good standing with the Russian government. We are also in good standing with the russian government.
Good luck, bud.
________________________________
From: EricGallagher ***@***.***>
Sent: 30 September 2022 04:15
To: OpenYiff/Kemono2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenYiff/Kemono2] Your App Steals from Content Creators (Issue #197)


Sad that you use your coding abilities to do something low like this. Your site has been reported to your host. If taken down, I will continue to report your site to any company that you try to host your site under.

**Comment by shinonomeme** [comment]
If I may politely ask, why in god's name have you presented your complaint in this workspace? That isn't what the issues page is for, and I think you know that there is little constructive end to coming here.
[Consider contacting the kemono.party instance administrator](mailto:admin@kemono.party) instead if you have no feature requests, bug reports, or development problems, as OpenYiff and the administration of that site are considered separate and independently-operating entities. Locking.
