### ISSUE TITLE
Duplicate posts, mismatch between the real and displayed post count

### ISSUE THREAD

**Issue by xvwyh** [OpenYiff/Kemono2#3]
Seems like the posts database can contain multiple posts with the same ID, and this creates an issue where the same post may appear multiple times in the /:service/user/:id listing. I did see the
> Multiple edits of the same post can appear on one page.

in the help page, but there is currently no way to access any of the "versions" of the post, because all the duplicate posts in the listing will have the same /:service/user/:user_id/post/:post_id URL containing only the non-unique post ID and nothing that would allow distinguishing between several versions of the same post.

Looking at the code, there is a discrepancy between queries
https://github.com/OpenYiff/Kemono2/blob/8583ddb78f0752f4e3ceb904ed56d66fafd43baf/server.py#L267
and
https://github.com/OpenYiff/Kemono2/blob/8583ddb78f0752f4e3ceb904ed56d66fafd43baf/server.py#L281

The first one - the listing - doesn't group by ID, so all the duplicates are not omitted, but the second one - the query of the total number of posts for that user - does group them, and so the duplicate posts are excluded from the total count. This creates a situation where the user of the website can continue paginating past the expected "end" of the listing (i.e. past "offset: 1234 / 1234") and still encounter new posts.

The way I'm seeing it, one of two actions need to be taken:
a) Group by ID in the listing query too, omitting duplicates, but this then needs ensuring that only the latest "version" is displayed, not the first one that's returned from the database.
b) Remove grouping by ID in the count query so that it matches the real number of displayed posts, but then there needs to be a way to access each particular version of the post, otherwise having them all displayed is pointless.

**Comment by BassOfBass** [comment]
That's a pretty old issue referencing a table which isn't used anymore. So it can be closed.
