### ISSUE TITLE
Updating to current version of Kemono produces Internal Server Error

### ISSUE THREAD

**Issue by marsrp1** [OpenYiff/Kemono2#44]
I've been using an older version of Kemono (the 'classic' one, so to speak) and wanted to upgrade to the newest version now.
Upon starting it and opening the page I get Error 500
```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
I tried to check the logs through docker (docker logs kemono) but it doesn't seem the output is very useful:
 ```
docker logs --since 180s kemono
[pid: 27|app: 0|req: 3/3] 127.0.0.1 () {32 vars in 321 bytes} [Sun Apr  4 11:01:44 2021] GET / => generated 290 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
 * Starting nginx nginx
   ...done.
*** Starting uWSGI 2.0.19.1 (64bit) on [Sun Apr  4 11:01:57 2021] ***
compiled with version: 7.5.0 on 03 February 2021 22:59:37
os: Linux-4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30)
nodename: 33955152032d
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /app
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/kemono.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.6.9 (default, Oct  8 2020, 12:12:24)  [GCC 8.4.0]
Python main interpreter initialized at 0x562ecdb55860
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
python threads support enabled
your server socket listen backlog is limited to 40000 connections
your mercy for graceful operations on workers is 60 seconds
mapped 166688 bytes (162 KB) for 2 cores
*** Operational MODE: threaded ***
mounting server:app on /
WSGI app 0 (mountpoint='/') ready in 0 seconds on interpreter 0x562ecdb55860 pid: 22 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22)
spawned uWSGI worker 1 (pid: 27, cores: 2)
[pid: 27|app: 0|req: 1/1] 192.168.1.3 () {42 vars in 854 bytes} [Sun Apr  4 11:02:09 2021] GET /?q=&service=&sort_by=indexed&order=asc&commit=Search => generated 290 bytes in 11 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
[pid: 27|app: 0|req: 2/2] 127.0.0.1 () {32 vars in 321 bytes} [Sun Apr  4 11:02:57 2021] GET / => generated 290 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 1)
[pid: 27|app: 0|req: 3/3] 127.0.0.1 () {32 vars in 321 bytes} [Sun Apr  4 11:03:57 2021] GET / => generated 290 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
```
As far as I can tell the config files are configured properly (the only difference from originals is the database username and password, which I also modified in docker-compose.yml).
Is there a way to see more detailed logs of kemono? (I remember when starting it directly with flask, without docker, there was output to console, but I don't know if it's possible to check this when ran through docker)

**Comment by kemono-bugs** [comment]
I've been getting this error as well during local testing, will investigate.

**Comment by marsrp1** [comment]
A small update, I managed to find the log file of kemono and found why it refused to start. The secret_key was not set anywhere in server.py. After setting it the app starts and I can open the main page! However... besides that almost nothing works. Artists page gives internal server error, Recently updated artists opens up fine, but clicking on any artist produces internal server error. Recent Posts opens up, but page layout is messed up. Clicking on any post also gives internal server error. Import, Requests and Login pages load up, I did not test them however.

Upon checking the logs I found this:
`ERROR:server:Exception on /artists [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 1185, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./src/pages/artists.py", line 36, in list
    results = get_top_artists_by_faves(offset, limit)
  File "./src/lib/artist.py", line 12, in get_top_artists_by_faves
    artists = redis.get(key)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 1187, in get_connection
    connection = self.make_connection()
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 1227, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 509, in __init__
    self.port = int(port)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
`
This is for the artists page, exact same is for any of the posts.

**Comment by BassOfBass** [comment]
Are you running from docker or manually?

**Comment by marsrp1** [comment]
It's through Docker. The previous version (the one that looks like this: [https://i.gyazo.com/6df426cdc4bd4ca539774dc1a6b3a8d2.png](https://i.gyazo.com/6df426cdc4bd4ca539774dc1a6b3a8d2.png) ) loads fine and works. But upon downloading the new one, doing modifications mentioned in the original issue report, and now adding the secret it doesn't work.

My docker ps looks like this:
```
dca70121e998        kemono2_kemono-app     "/bin/sh -c 'service…"   16 seconds ago      Up 12 seconds (health: starting)   0.0.0.0:8000->80/tcp     kemono
8945c86ae616        openyiff/kitsune       "/bin/sh -c 'service…"   16 seconds ago      Up 12 seconds                                               kemono-archiver
8fc8c1acf193        healthcheck/postgres   "docker-entrypoint.s…"   About an hour ago   Up About an hour (healthy)         0.0.0.0:5433->5432/tcp   kemono-db
81c0c27b387a        willfarrell/autoheal   "/docker-entrypoint …"   About an hour ago   Up About an hour (healthy)                                  kemono-autoheal
2d102f7acd95        redis:6.2.0            "docker-entrypoint.s…"   About an hour ago   Up About an hour                   6379/tcp                 kemono-redis

```

**Comment by BassOfBass** [comment]
By _old version_ you don't mean [kemono 1](https://github.com/OpenYiff/Kemono), right?

**Comment by marsrp1** [comment]
No no, it's python based, this one. Just an older 'build' (from February of this year)

**Comment by BassOfBass** [comment]
@kemono-bugs there are a lot of calls to `redis` in the stack, is this because env variables are not set? I see there is no redis-related variables in [`.env.example`](https://github.com/OpenYiff/Kemono2/blob/master/.env.example)(they were removed due to rollback, but aren't reinstated thereafter). I assume docker image uses the same logic as manual installation, i.e. copying the contents of `.env.example` to `.env`, so no redis variables in the end.

**Comment by marsrp1** [comment]
Well, I can confirm that it's lack of those not being in .env
I added the following two lines to my .env:
```
REDIS_HOST=kemono-redis
REDIS_PORT=6379
```
Now, I still get an error, but it's related to the database. I need to update db schema to the new one (missing account_artist_favorite for example). So yeah, seems that this doesn't work because of two things:

1. Missing app.secret_key in server.py, perhaps this can be also set through .env file
2. Lack of redis in .env

**Comment by BassOfBass** [comment]
Try setting `SECRET_KEY` in `flask.cfg`.
As for updating the schema, shouldn't docker image have up to date schemas anyway, since kitsune includes migrations scripts?

**Comment by marsrp1** [comment]
Removed it from server.py and added it to flask.cfg, it does work as it should, yes.

Yes, it updated the schema now. I don't know if I'm updating it wrong (I do it by downloading current kemono from github, modifying .env and such, then issuing docker-compose build and docker-compose up -d), but it turned out... Kitsune doesn't get updated that way. It just gives 'using an image, skipping'. I forced an update by deleting kitsune's image and now the database is updated and works fine.

**Comment by BassOfBass** [comment]
Did the layout issue go? And if not, what browser are you using?

**Comment by marsrp1** [comment]
You know, that's a funny thing, at the time, even with database fixed, the layout was still messed up. But I just opened it up again (did a full restart of my server tho) and the layout is perfectly fine.

**Comment by GlassedSilver** [comment]
This really doesn't play nicely with portainer, does it? :/

**Comment by BassOfBass** [comment]
Why wouldn't it? It looks like a GUI on top of docker.

**Comment by GlassedSilver** [comment]
Maybe it's just me being a novice at portainer, because so far I've mostly used unRAID's DockerMan and also did some single container (so unstacked) deployments where a "community application" (pre-made template for unRAID's DockerMan) wasn't available.

When I try to deploy using Portainer all I get is that it cannot find the env file...

Even if I specify "env_file:=.env.example" in the environment variables.

But maybe I'm missing something.

**Comment by BassOfBass** [comment]
Did you create files according to [these instructions](https://github.com/OpenYiff/Kemono2/blob/master/README.md#with-docker)?

**Comment by GlassedSilver** [comment]
I'm not using docker-compose from the command line so I don't have a workdir before Portainer initializes the stack.

**Comment by BassOfBass** [comment]
But you don't need to use `docker-compose`, just do the copy commands. Presumably Portainer will pick up all docker-related configs.

**Comment by marsrp1** [comment]
Returning to the original issue, I see that everything missing for redis has been now added to github, there is just one more thing that's necessary. Redis section of docker-compose needs restart: unless-stopped
Currently it has nothing, so once docker is restarted for any reason (ie. machine reboot) redis doesn't start with the other services.
