### ISSUE TITLE
Non unicode filenames being renamed to "Untitled.jpe"

### ISSUE THREAD

**Issue by jojo935** [OpenYiff/Kemono2#46]
Not sure where in the import process it does this but most times a Japanese artist's posts are imported in .jpeg format, the art is stripped of its original name and renamed "Untitled.jpe". This basically makes it impossible to save to disk without changing both the file extension and file name. It opens while being a .jpe file but the name is still "Untitled". Multiple pictures within a post usually have a "-x" suffix, so it'd be "Untitled-1.jpe" for example when the original file should be "(insert japanese file name here).jpeg".

**Comment by BassOfBass** [comment]
@RandomSuperUser is `jpe` [in this regexp](https://github.com/OpenYiff/Kemono2/blame/30d2bc21858afc68578415de79c82717102116d7/src/pages/post.py#L65) at fault? For extension part at least.

**Comment by a940802a** [comment]
you guys patreon renzukiharai https://www.patreon.com/user?u=12214986
Kemono.party 
and
ス○ブラと巨乳を愛する会 (あき)
https://fantia.jp/fanclubs/4071
kemono.party ok

**Comment by jojo935** [comment]
> you guys patreon renzukiharai https://www.patreon.com/user?u=12214986
> Kemono.party
> and
> ス○ブラと巨乳を愛する会 (あき)
> https://fantia.jp/fanclubs/4071
> kemono.party ok

You really are insufferable.I hope you never have children, for them to be as braindead an incel as you.

**Comment by jojo935** [comment]
> you guys patreon renzukiharai https://www.patreon.com/user?u=12214986
> Kemono.party
> and
> ス○ブラと巨乳を愛する会 (あき)
> https://fantia.jp/fanclubs/4071
> kemono.party ok

We don't even support fanita, you wet flannel.
