### ISSUE TITLE
All images give http 404 error

### ISSUE THREAD

**Issue by hyvamiesh** [OpenYiff/Kemono2#60]
Running latest docker build, pulled the 25th of may.
I've set the SECRET_KEY in flask.cfg
Changed the outward server port to 8001
otherwise no changes. The files can be found in /storage.

**Comment by BassOfBass** [comment]
Changed the port where? In the `docker-compose.yml`?

**Comment by hyvamiesh** [comment]
Yes

**Comment by marsrp1** [comment]
Copy a link of the image and change the port in the link to 8000 and see if it loads. If it does, then likely nginx is running on 8000, as docker-compose.yml only changes the port of Kemono

**Comment by hyvamiesh** [comment]
That won't work, as I'm running another service on port 8000

**Comment by hyvamiesh** [comment]
Pulled the update yesterday and now everything is working fine.
Closing issue.
