### ISSUE TITLE
Kemono2 not serving thumbnails and full images

### ISSUE THREAD

**Issue by marsrp1** [OpenYiff/Kemono2#7]
Hello.
I've set up Kemono2 and Kitsune, both running with flask. Everything seems fine, the webpage works, upon submitting session ID Kitsune scrapes over and downloads everything off Patreon. However, as soon as I open any post no images load.
I can confirm that thumbnails get in fact generated properly, the images do get placed in thumbnail/[filetype]/[artistid]/[postid].
Attached are screenshot of the webpage (running in Chrome) as well as screenshot of Kemono2 logs.
![Webpage](https://user-images.githubusercontent.com/78277298/106380403-47829200-63b2-11eb-9da3-cbf8c912c8c5.PNG)
![KemonoLog](https://user-images.githubusercontent.com/78277298/106380405-481b2880-63b2-11eb-837d-50172914673b.PNG)

**Comment by kemono-bugs** [comment]
You have to front the program with a webserver like Nginx. The Docker setup can do this for you.
