### ISSUE TITLE
Kemono keeps saying my posts are "automated"

### ISSUE THREAD

**Issue by SuuLucoa** [OpenYiff/Kemono2#70]
I've been trying to comment to the forum/thread for weeks and I still can't post a comment without getting a "Your request looks automated; Post discarded." page. 
At first I thought it was just random, but it's been doing it EVERY SINGLE TIME! 
How can I give feedback if the site won't let me do it without letting a discard bot claim that my comments are automated!?

**Comment by kemono-bugs** [comment]
Read the front page of the site. Yes, I know Partychan is down. No, I can't do anything about it.
