### ISSUE TITLE
Patreon importer doesn't import posts that have no name (~2016 year)

### ISSUE THREAD

**Issue by marsrp1** [OpenYiff/Kemono2#8]
Wasn't sure if it should be in Kitsune (importer) or Kemono2 (database schema) so decided to do it here.
Way back Patreon allowed creators to make posts without any title. Currently, the patreon importer does scrape those posts, but treats the title as null, which upon INSERT into the database throws the following error:
```
Error while importing 6186055: null value in column "title" of relation "posts" violates not-null constraint
DETAIL:  Failing row contains (6186055, 613827, patreon, null, , {}, f, 2021-02-03 19:41:39.861609, 2016-08-01 03:34:38, 2016-08-01 03:34:38, {"name": "kobold.png", "path": "/files/613827/6186055/kobold_1.p..., {"{\"name\": \"kobold_1.png\", \"path\": \"/attachments/613827/6...).
```
Currently, I was able to fix it by modifying in postgres the posts table and removing the "NOT NULL" constraint from 'name' column. After that the posts got imported and the kemono webpage loads them properly, the title is simply displayed as "None".

Possible fixes: The fix I did where database doesn't have "NOT NULL" on this column, assuming it doesn't possibly break anything. 
Another fix, would be modifying the importer so if the title is null, it instead tries to insert an empty string ''.

**Comment by kemono-bugs** [comment]
Fixed. Kitsune now enters an empty string when the title is null.
