### ISSUE TITLE
nginx is unhealthy?

### ISSUE THREAD

**Issue by GlassedSilver** [OpenYiff/Kemono2#80]
Not sure what to do here, when building and running as per instructions I don't even get to start all containers.

`ERROR: for kemono-nginx  Container "69d994f20964" is unhealthy.
ERROR: Encountered errors while bringing up the project.`

All nginx related stuff did pull. Not sure what the issue could be.

Is it safe to remove the nginx volume maybe?

**Comment by BassOfBass** [comment]
Does this command have any meaningful errors?
```shell
docker logs kemono
```

**Comment by GlassedSilver** [comment]
Thank you, that did it!

I had a syntax error in my flask.cfg.

Turns out I must have recreated the file without putting the path to the `SECRET_KEY` in single quotes! (basically: `SECRET_KEY=‘<path to key on host>‘`)
D‘uh!

Thank you so much!
