### ISSUE TITLE
Attempting to "favorite" an artist's page while logged out results in a permanently repeating error.

### ISSUE THREAD

**Issue by sixinchfootlong** [OpenYiff/Kemono2#91]
Steps to reproduce:

1. Clear all of your cookies and local storage so that you're fully logged out.
2. Go to an artists page and attempt to "favorite" them.
   - This will throw an error and redirect you to the login page.
3. _Don't log in._  Just go back to browsing anonymously.

From this point on, any time you visit _any_ artist's page, you'll get _two_ JavaScript alert boxes.  
The first says "Error: Error 401:", the second says "Could not retrieve favorite artists".
What's annoying is that this error is _sticky_.  Even if you clear your cookies you'll still get the error.  The only way to stop it is to clear your local storage, register a new account, or log in to an existing account.

I haven't dug into the code yet, but it seems to be caused by the `favs` value getting set to `undefined`.  Each subsequent page load will attempt to pull your favorite artists regardless if you're logged in or not.

It appears that PR #88 might be an attempt to fix this.

**Comment by BassOfBass** [comment]
That was fixed a while ago.
