### ISSUE TITLE
Forms reverting to default options on refresh

### ISSUE THREAD

**Issue by localappdata** [OpenYiff/Kemono2#96]
Forms will revert to default options on a page refresh due to how they work
Workaround available by changing pages manually

**Comment by BassOfBass** [comment]
That's how forms work in general.
There is a way to save their state in `localStorage` and I am working on a module allowing the pages to save their local settings there without namespace pollution and minimal boilerplate in the page's script. But no ETA on its release and merge.

**Comment by localappdata** [comment]
Thanks for the reply, get args isnt an option for such forms I guess?

**Comment by BassOfBass** [comment]
Not sure what you mean, but any server-side interaction requires a request to that server in the first place. A page refresh is just a request to the page. The server doesn't know the content of forms without the prior submission of said forms.

**Comment by BassOfBass** [comment]
Let's just say the idea won't come true any time soon.
